debug: true

# Deploy-time configurable list of role bindings for identity
# provided usernames
admin_usernames: # Global portal admins
  - bob@example.com
tre_ops_staff_usernames: # Trusted research environment staff
  - bob@example.com
ig_ops_staff_usernames: # Information governance operations staff
  - bob@example.com
dsh_ops_staff_usernames: # Data safe haven operations staff
  - bob@example.com

db:
  dsn: host=postgres user=postgres password=postgres dbname=dev sslmode=disable TimeZone=UTC # pragma: allowlist secret

s3:
  dev: # Required S3 config in dev
    host: s3:8333 # Host:port of the s3 service

  bucket: bucket-name # Must exist in staging/prod and will be created in dev. In dev it must match the value in s3/entrypoint.sh
  region: eu-west-2 # AWS region the bucket exists in

  # Access keys for user with S3:GetObject and S3:PutObject on the bucket
  access_key_id: s3
  secret_access_key: s3 # pragma: allowlist secret

entra:
  # EntraID app registration with User.Read.All & User.Invite.All application permissions
  tenant_id: <CHANGE_ME>
  client_id: <CHANGE_ME>
  client_secret: <CHANGE_ME>
  invite_redirect_url: <CHANGE_ME> # where you want to send the user when they accept the invite, eg. http://localhost:8000/profile
  primary_domain: <CHANGE_ME> # eg. arctretest.onmicrosoft.com
  invited_user_group_id: <CHANGE_ME> # found in the Azure portal, eg Invited Users group

  # Mail app details, these may be the same as the above but don't have to be (eg in the case of different tenants)
  mail_tenant_id: <CHANGE_ME>
  mail_client_id: <CHANGE_ME>
  mail_client_secret: <CHANGE_ME>
  mail_user_principal: <CHANGE_ME> # eg. rp2@ucl.ac.uk, found in entra by searching for the mailbox

url: <CHANGE_ME> # eg. https://portal.arc.ucl.ac.uk
tre:
  users: # Map of usernames to passwords for HTTP basic auth
    username: password # pragma: allowlist secret
